export const BLOGS_REPOSITORY = Symbol('BLOGS_REPOSITORY');
export const BLOGS_QUERY_REPOSITORY = Symbol('BLOGS_QUERY_REPOSITORY');

export const POSTS_REPOSITORY = Symbol('POSTS_REPOSITORY');
export const POSTS_QUERY_REPOSITORY = Symbol('POSTS_QUERY_REPOSITORY');

export const COMMENTS_REPOSITORY = Symbol('COMMENTS_REPOSITORY');
export const COMMENTS_QUERY_REPOSITORY = Symbol('COMMENTS_QUERY_REPOSITORY');

export const LIKES_REPOSITORY = Symbol('LIKES_REPOSITORY');
export const LIKES_QUERY_REPOSITORY = Symbol('LIKES_QUERY_REPOSITORY');
