export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');
export const USERS_QUERY_REPOSITORY = Symbol('USERS_QUERY_REPOSITORY');

export const AUTH_QUERY_REPOSITORY = Symbol('AUTH_QUERY_REPOSITORY');
