export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');
export const USERS_QUERY_REPOSITORY = Symbol('USERS_QUERY_REPOSITORY');

export const AUTH_QUERY_REPOSITORY = Symbol('AUTH_QUERY_REPOSITORY');

export const AUTH_SESSIONS_REPOSITORY = Symbol('AUTH_SESSIONS_REPOSITORY');
export const SECURITY_DEVICES_QUERY_REPOSITORY = Symbol(
  'SECURITY_DEVICES_QUERY_REPOSITORY',
);
